project_id = "ddgsedoaepxqcduvrksw"

[functions.generate-script]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-tts]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.agent-orchestrator]
verify_jwt = false
